### ISSUE TITLE
Using vue-cycle with @cycle/state and without templates

### ISSUE THREAD

**Issue by synchromesh** [TimurKiyivinski/vue-cycle#6]
Hi Timur,

Firstly, thanks very much for writing `vue-cycle`. I'm new to Vue but I have had some experience getting React, Redux, Cycle.js and `redux-cycles` working together. Now I'm trying to do the same thing with Vue, Cycle.js and `vue-cycle`, using `@cycle/state` for state management.

I'm also trying to avoid using templates, so I'm wondering how to get the equivalent of the `v-xstream` directive in JavaScript. Can you offer any advice on how to do this?

Also have you looked at using `@cycle/state` with `vue-cycle`? If so, do you have any code examples that you could share?

Thanks again,

John :^P

**Comment by kiyui** [comment]
> how to get the equivalent of the `v-xstream` directive in JavaScript

I'm not sure what you mean by this. Do you want to use `xstream`'s `fromEvent` function directly?

If you want just the `v-xstream` directive, you can just do:
```javascript
// Global
import { VueCycleDomDirective } from 'vue-cycle'
Vue.directive('xstream', VueCycleDomDirective)

// Component
export default {
  ...component,
  directives: { xstream: VueCycleDomDirective }
}
```
You can also check out [vue-rx](https://github.com/vuejs/vue-rx) :grin: 

> have you looked at using `@cycle/state` with `vue-cycle`

Yuups, I actually have an example lying somewhere using the original [cycle-onionify](https://github.com/staltz/cycle-onionify), though I will have to get back to you on that.

However, you can accomplish just the same using:
```javascript
import { withState } from '@cycle/state'

export default {
  ...component,
  $_cycle_run (app) {
    const wrappedMain = withState(app.bind(this))
    run (wrapperMain, { ...drivers })
  }
}
```
In the same way that the current plugin makes use of the `this` scope inside `$_cycle_app`.

**Comment by kiyui** [comment]
Closing stale issue.

**Comment by synchromesh** [comment]
Thanks very much for your prompt and detailed answer, sorry for not responding sooner.

In the end I went back to just using Cycle.js (and Snabbdom) in order to keep things simple (and well-documented). I would like to use Vue in the future with Cycle.js, so it would be great if you could publish the example you mentioned.

Cheers,

John :^P

(EDIT: I didn't mean to imply that `vue-cycles` was not well-documented. But you can never have too many examples! I look forward to returning to `vue-cycles` once I have a bit more experience and can make better use of the source code itself.)
